default: &default
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: dotamastery_development
  adapter: postgresql
  encoding: unicode

test:
  <<: *default
  database: db/test.sqlite3
  adapter: sqlite3

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 25
